name: weather_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  provider: any
  get_it: ^7.7.0
  device_preview_plus: ^2.1.3
  http: ^1.2.2
  icons_launcher: ^3.0.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  lottie: ^3.1.2
  mockito: ^5.4.4
  objectbox: ^4.0.1
  shared_preferences: ^2.3.2
  objectbox_flutter_libs: ^4.0.1
  path_provider: ^2.1.4
  geolocator: ^13.0.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/

flutter_native_splash:
  color: "#262626"
  image: assets/images/app_logo.png
  android: true
  ios: true

  android_12:
    color: "#262626"
    image: assets/images/app_logo.png

icons_launcher:
  image_path: "assets/images/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
